### ISSUE TITLE
Blockchain download never completes in MacOS client

### ISSUE THREAD

**Issue by krisjoseph** [incentivetoken/offspring#3]
When downloading the blockchain using Offspring 0.4.1, updates stop as soon as a new block is received.

I've actually had this problem for the last several versions, but since it keeps coming up, I thought I'd report it.

Actions:
- go to File -> Delete blockchain
- blockchain begins to download and continues until a new block is received
- when the new block is received, blockchain download ceases and does not continue

**Comment by incentivetoken** [comment]
I dont understand. As far as I can tell there is no difference between downloading blocks and receiving a new block. As far as Offspring is concerned that's the same thing.

Can you tell me how you can tell that a new block is received? What do you see to indicate that? 

Also.. What do you see (what does the statusbar say) when the download ceases?

**Comment by krisjoseph** [comment]
I have NO idea what's happening in the background, but the behaviour is a little odd:  after starting the blockchain download, the client eventually receives a new block.  The timestamp on the block suggests it's "current", but the blockchain isn't done downloading yet, at that point.  Nonetheless, in the "advanced" tab I see blocks numbered up to 30102, and then the NEW block gets numbered as the next number (in my current case, 30103, even though the current block height is over 100000).  After that, no more blocks are downloaded.

This capture is from yesterday, and shows what I see in the window:

![screen shot 2014-04-01 at 10 32 29 pm](https://cloud.githubusercontent.com/assets/7120606/2587460/a00f0bbc-ba20-11e3-9e77-b92602b9443c.png)

Note the small number of active peers.  It's possible that this is just a "display issue".  I say that because when I started the client tonight, it managed to get the remainder of the blockchain without problems -- and I have many more active peers listed than I did yesterday.

**Comment by incentivetoken** [comment]
Thanks for the screenshot, that clears up things. I think you are on a blockchain fork. The fact that block 30103 has date 31-3-2014 proves this. The value in the height cell comes directly from the NXT Block object, which can be seen here https://github.com/incentivetoken/offspring/blob/89c248cc36264a383b0e62de0e8070a460f92f34/com.dgex.offspring.application/src/com/dgex/offspring/application/parts/RecentBlocksViewer.java#L70 so it's not Offspring misinterpreting that.

I suggest you to delete everything in your Offspring folder except your offspring.wallet file. This includes the blockchain (nxt_db folder) and all config files. Your Offspring folder is located in your HOME folder.

It might be that since you say you have had this for a few versions that an old 'wellknownpeers' value has been messing things up for you. Deleting the config files (offspring.config) can fix this.

**Comment by incentivetoken** [comment]
Fixed in 0.4.2e turns out there was an error where Offspring accepted to display newly pushed (forged) blocks while downloading the blockchain. This is no longer the case. It was a display error only btw. Thanks for reporting.
