### ISSUE TITLE
Nxt 4.5 for Mac

### ISSUE THREAD

**Issue by TomJST** [incentivetoken/offspring#7]
get fatal error message when I launch; message also says try deleting Nxt database, but not sure what that means? Also, when I go back to older version (4.1), I now get the same fatal error message for this version to.

**Comment by incentivetoken** [comment]
In order to help you I need the following information. 
1. What does the error say?
2. Did you successfully run Offspring before
3. Can you access the offspring.log file in your HOME/Offspring directory (sorry still not sure where the default HOME folder on a Mac is) 

The contents of your log should not contain any sensitive information but you might want to check anyway. If you decide to share the contents of your log you can do so publicly through a service like http://paste.ubuntu.com/ or you can send me an email at incentivetoken@gmail.com.

But probably as is almost always the case your blockchain files got corrupted some how. Best to delete the blockchain then. Your blockchain can be deleted by deleting the following folder:

HOME/Offspring/nxt_db

Not sure where HOME is? Check out this apple support page http://support.apple.com/kb/ht2549

**Comment by TomJST** [comment]
The error dialog box has this: initializing, then get a box with title of “NXT initialization Error” with red stop sign below with the following msg: “ A fatal error occurred initializing NXT. If this keeps occurring consider to delete NXT database folder”

I found and deleted the nxt_db and everything restarted ok. However, one issue that is confusing is as follows:
I had two accounts that started about a week ago with the following NXT quantity. Account 1) had 8047 NXT and account 2) had 2769 NXT. About a week ago forging started showing just a few minutes to forge in both accounts (whereas, before the forging time was hundreds of hours). And over several days, the first account and added 41 NXT and the second account had added 26 NXT, apparently due to forging (I had forging checked on); this is with version 4.1. Now with version 4.5, when I load those accounts, my old totals are showing and I’ve lost the apparent new forged NXT. What is causing this and did I really have 41 and 26 NXT forged or is it a bug in the system.

thanks for your help

Jon

**Comment by incentivetoken** [comment]
Sounds like you were on a fork, a part of the network did not agree with the rest of the network about what blockchain was the winner. Reason probably being the forks occurring because of the big changes made to core NXT in that time. You probably did forge the blocks but unfortunately on the fork. With those amounts of NXT you are not likely to forge any time soon.

Glad I could help.
